package analyzer

import (
	"context"

	"google.golang.org/protobuf/proto"
)

// Analyzer is the generic plugin interface for compliance analysis.
//
// The type parameter T is the proto.Message type this analyzer accepts
// as input, providing compile-time safety. Implementations must be safe
// for concurrent use.
//
// Each analyzer declares its dependencies via DependsOn. The Registry
// uses these declarations to build a DAG for execution ordering.
type Analyzer[T proto.Message] interface {
	// Name returns the unique identifier for this analyzer.
	Name() string

	// DependsOn returns the names of analyzers that must complete
	// before this one can execute. Return nil or empty for no dependencies.
	DependsOn() []string

	// GenerateWork produces tasks from an input and configuration.
	// Each task is a unit of work that can be dispatched independently
	// (e.g., to an LLM worker via NATS).
	GenerateWork(ctx context.Context, input T, config AnalyzerConfig) ([]Task, error)

	// Aggregate combines completed task results into a final output.
	Aggregate(ctx context.Context, results []TaskResult) (*Output, error)

	// ResultSchema returns an empty proto.Message representing the
	// schema of results this analyzer produces. Used for validation
	// and discovery.
	ResultSchema() proto.Message
}

// RegisteredAnalyzer is the type-erased wrapper stored in the Registry.
//
// It provides the same contract as Analyzer[T] but accepts proto.Message
// instead of a concrete type. The type assertion from proto.Message to T
// happens inside the wrapper generated by Register[T], not in user code.
type RegisteredAnalyzer interface {
	// Name returns the unique identifier for this analyzer.
	Name() string

	// DependsOn returns the names of analyzers that must complete
	// before this one can execute.
	DependsOn() []string

	// GenerateWorkFromProto produces tasks from a proto.Message input.
	// Returns an error if the input type does not match the analyzer's
	// expected type T.
	GenerateWorkFromProto(ctx context.Context, input proto.Message, config AnalyzerConfig) ([]Task, error)

	// Aggregate combines completed task results into a final output.
	Aggregate(ctx context.Context, results []TaskResult) (*Output, error)

	// ResultSchema returns an empty proto.Message representing the
	// schema of results this analyzer produces.
	ResultSchema() proto.Message

	// InputType returns the full protobuf message name of the input
	// type this analyzer expects (e.g., "crosscodex.v1.Control").
	// Used for validation and discovery.
	InputType() string
}
