package analyzer

import (
	"time"

	"google.golang.org/protobuf/proto"
)

// Task represents a unit of work generated by an analyzer.
// Each task can be dispatched independently (e.g., to an LLM worker via NATS).
type Task struct {
	// JobID is the parent job identifier linking related tasks.
	JobID string

	// TaskID uniquely identifies this task.
	TaskID string

	// TaskType is the name of the analyzer that produced this task.
	TaskType string

	// Payload is the work item payload, specific to the analyzer.
	Payload proto.Message
}

// TaskResult contains the outcome of a completed task.
type TaskResult struct {
	// TaskID matches the Task.TaskID this result corresponds to.
	TaskID string

	// TaskType is the name of the analyzer that produced the original task.
	TaskType string

	// Result is the result payload. Must conform to the analyzer's ResultSchema.
	Result proto.Message

	// Error is non-nil if the task failed.
	Error error

	// Duration is the wall-clock time the task took to execute.
	Duration time.Duration
}

// AnalyzerConfig holds configuration passed to an analyzer's GenerateWork method.
type AnalyzerConfig struct {
	// Parameters are analyzer-specific key-value configuration pairs.
	Parameters map[string]string
}

// Output is the aggregated result from an analyzer after all its tasks complete.
type Output struct {
	// AnalyzerName identifies which analyzer produced this output.
	AnalyzerName string

	// Data is the aggregated result payload.
	Data proto.Message

	// Metadata holds execution metadata (timing, counts, model versions, etc.).
	Metadata map[string]string
}
