-- Requires analyzer tables: candidate pairs, votes, and consensus results.
-- Tenant isolation via RLS (consistent with migration 007 pattern).

-- Candidate pairs (generated by candidate analyzer)
CREATE TABLE IF NOT EXISTS requires_candidates (
    tenant_id        TEXT NOT NULL,
    job_id           TEXT NOT NULL,
    source_id        TEXT NOT NULL,
    target_id        TEXT NOT NULL,
    aggregate_score  REAL NOT NULL,        -- Weighted score from generators
    provenance       JSONB NOT NULL,       -- Array of {generator, score, weight, metadata}
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (tenant_id, job_id, source_id, target_id)
);

CREATE INDEX idx_requires_candidates_job ON requires_candidates(tenant_id, job_id);

ALTER TABLE requires_candidates ENABLE ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON requires_candidates
    USING (tenant_id = current_setting('app.current_tenant', true));

GRANT SELECT, INSERT, UPDATE, DELETE ON requires_candidates TO app_user;

-- Voting results (one row per model × sample × pair)
CREATE TABLE IF NOT EXISTS requires_votes (
    tenant_id        TEXT NOT NULL,
    job_id           TEXT NOT NULL,
    source_id        TEXT NOT NULL,
    target_id        TEXT NOT NULL,
    model            TEXT NOT NULL,
    sample_index     INT NOT NULL,
    requires         BOOLEAN,              -- NULL if vote errored
    justification    TEXT,
    confidence       TEXT,                 -- HIGH, MEDIUM, LOW
    raw_response     TEXT,
    vote_weight      REAL NOT NULL DEFAULT 1.0,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (tenant_id, job_id, source_id, target_id, model, sample_index)
);

CREATE INDEX idx_requires_votes_pair ON requires_votes(tenant_id, job_id, source_id, target_id);

ALTER TABLE requires_votes ENABLE ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON requires_votes
    USING (tenant_id = current_setting('app.current_tenant', true));

GRANT SELECT, INSERT, UPDATE, DELETE ON requires_votes TO app_user;

-- Consensus results (denormalized for fast queries)
CREATE TABLE IF NOT EXISTS requires_consensus (
    tenant_id              TEXT NOT NULL,
    job_id                 TEXT NOT NULL,
    source_id              TEXT NOT NULL,
    target_id              TEXT NOT NULL,
    requires               BOOLEAN NOT NULL,
    confidence_fraction    REAL NOT NULL,
    unanimous              BOOLEAN NOT NULL,
    valid_vote_count       INT NOT NULL,
    total_vote_count       INT NOT NULL,
    total_weight           REAL NOT NULL,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (tenant_id, job_id, source_id, target_id)
);

CREATE INDEX idx_requires_consensus_decision ON requires_consensus(tenant_id, job_id, requires);

ALTER TABLE requires_consensus ENABLE ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON requires_consensus
    USING (tenant_id = current_setting('app.current_tenant', true));

GRANT SELECT, INSERT, UPDATE, DELETE ON requires_consensus TO app_user;
